steps:
  submodules:
    image: alpine/git
    commands:
      - git submodule update --init --recursive
  dry-run:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO_OWNER##mu-}/${CI_REPO_NAME}
      platforms: linux/amd64
      dry-run: true
when:
  - event: pull_request
